spring:
  application:
    name: announcement

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    webhook-path: /telegram/webhook

app:
  base-url: https://astrointel.onrender.com

server:
  port: 8080