spring:
  application:
    name: announcement

telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  botUsername: ${TELEGRAM_BOT_USERNAME}

app:
  base-url: https://astrointel.onrender.com

server:
  port: 8080