spring:
#  profiles:
#    active: local
  application:
    name: announcement

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    webhook-path: /telegram/webhook

app:
  base-url: https://astrointel.onrender.com
  version: 1.1.2
  features:
    - Update feature add asset (registration format)
    - Summary asset (new format)

server:
  port: 8080

gist:
  github-token: ${GITHUB_TOKEN}
  gist-id: ${GIST_ID}

google:
  api:
    key: ${GEMINI_KEY}