spring:
  application:
    name: announcement

telegram:
  bot:
    token: 123
    username: 123
    webhook-path: /telegram/webhook

app:
  base-url: https://astrointel.onrender.com  # your Render domain

server:
  port: 8080


gist:
  github-token: N/A
  gist-id: N/A
